---
title: "Exploring Arabica Data"
output: pdf_document
date: "2024-04-04"
---

```{r load csv, message = FALSE}
library(readr)
library(tidyverse)
arabica <- read_csv("arabica_data_cleaned.csv")

dim(arabica)
```

```{r characteristic subsets}
flavor_arabica <- arabica %>%
  select(Country.of.Origin, Flavor) %>%
  rename("Country of Origin" = Country.of.Origin)

acidity_arabica <- arabica %>%
  select(Country.of.Origin, Acidity) %>%
  rename("Country of Origin" = Country.of.Origin)

sweetness_arabica <- arabica %>%
  select(Country.of.Origin, Sweetness) %>%
  rename("Country of Origin" = Country.of.Origin)

aroma_arabica <- arabica %>%
  select(Country.of.Origin, Aroma) %>%
  rename("Country of Origin" = Country.of.Origin)

total_arabica <- arabica %>%
  select(Country.of.Origin, Total.Cup.Points) %>%
  rename("Country of Origin" = Country.of.Origin,
         "Total Cup Points" = Total.Cup.Points)
```

```{r top ten tables}
flavor_top10 <- flavor_arabica %>% 
  slice_max(n = 10, order_by = Flavor)
flavor_top10

acidity_top10 <- acidity_arabica %>% 
  slice_max(n = 10, order_by = Acidity)
acidity_top10

sweetness_top10 <- sweetness_arabica %>% 
  slice_max(n = 10, order_by = Sweetness)
sweetness_top10

aroma_top10 <- aroma_arabica %>% 
  slice_max(n = 10, order_by = Aroma)
aroma_top10

total_top10 <- total_arabica %>% 
  slice_max(n = 10, order_by = `Total Cup Points`)
total_top10

```

```{r}
flavor_countries <- unique(flavor_top10$`Country of Origin`)
aroma_countries <- unique(aroma_top10$`Country of Origin`)
intersect(flavor_countries, aroma_countries)

flavor_countries <- unique(flavor_top10$`Country of Origin`)
sweetness_countries <- unique(sweetness_top10$`Country of Origin`)
intersect(flavor_countries, sweetness_countries)

flavor_countries <- unique(flavor_top10$`Country of Origin`)
total_countries <- unique(total_top10$`Country of Origin`)
intersect(flavor_countries, total_countries)

flavor_countries <- unique(flavor_top10$`Country of Origin`)
acidity_countries <- unique(acidity_top10$`Country of Origin`)
intersect(flavor_countries, acidity_countries)
```





