---
title: "Aroma Mapping"
output: pdf_document
date: "2024-19-04"
---
```{r message = F}
library(tmap)
library(sf)
library(tidyverse)
data("World")

arabica <- read_csv("../data/arabica_data_cleaned.csv")
robusta <- read_csv("../data/robusta_data_cleaned.csv")
merged <- read_csv("../data/merged_data_cleaned.csv")

aroma_arabica <- arabica %>%
  select(Country.of.Origin, Aroma) %>%
  rename("Country of Origin" = Country.of.Origin) %>%
  mutate(`Country of Origin` = recode(`Country of Origin`,
         "Cote d?Ivoire" = "Cote d'Ivoire",
         "Tanzania, United Republic Of" = "Tanzania",
         "Laos" = "Lao PDR",
         "United States (Puerto Rico)" = "Puerto Rico",
         "United States (Hawaii)" = "United States")) %>% 
  filter(`Country of Origin` != "Mauritius") #Had to remove because World data for some reason doesnt have this country?

aroma_robusta <- robusta %>%
  select(Country.of.Origin, Fragrance...Aroma) %>%
  rename("Country of Origin" = Country.of.Origin,
         "Aroma" = Fragrance...Aroma)

aroma_merged <- merged %>%
  select(Country.of.Origin, Aroma) %>%
  rename("Country of Origin" = Country.of.Origin) %>%
  mutate(`Country of Origin` = recode(`Country of Origin`,
         "Cote d?Ivoire" = "Cote d'Ivoire",
         "Tanzania, United Republic Of" = "Tanzania",
         "Laos" = "Lao PDR",
         "United States (Puerto Rico)" = "Puerto Rico",
         "United States (Hawaii)" = "United States")) %>% 
  filter(`Country of Origin` != "Mauritius") 
```


```{r arabica tables}
countries <- World %>%
  select(name, iso_a3) %>%
  rename("Country of Origin" = name) #This gives me countries and their locations on the world map

aroma_mean_arabica <- aroma_arabica %>%
  filter(!is.na(`Country of Origin`)) %>% #One value didnt have a country paired so I removed it
  group_by(`Country of Origin`) %>%
  summarize(`Aroma Mean` = mean(Aroma)) #This gives me mean values for each country's aroma reviews

aroma_world_arabica <- merge(countries, aroma_mean_arabica, by.x = "Country of Origin", by.y = "Country of Origin", all.x = TRUE) #This merges the mean values with countries so I can map them
```

```{r arabica mapping}
min(aroma_world_arabica$`Aroma Mean`, na.rm = TRUE)
max(aroma_world_arabica$`Aroma Mean`, na.rm = TRUE)

coffee_palette <- c("#FFEBCD", "#D2B48C", "#8B4513")
aroma_breaks <- c(7.0, 7.3, 7.6, 7.9, 8.2, 8.4)

aroma_tm_arabica <- tm_shape(aroma_world_arabica) +
  tm_polygons("Aroma Mean", title = "Aroma (Arabica)", palette = coffee_palette, 
              breaks = aroma_breaks, style = "quantile", id = "Aroma Mean") +
  tm_text("iso_a3", size = "AREA", just = "center") +
  tm_layout() +
  tm_view(text.size.variable = TRUE)


tmap_mode("view")
tmap_leaflet(aroma_tm_arabica)
```

```{r robusta tables}
aroma_mean_robusta <- aroma_robusta %>%
  filter(!is.na(`Country of Origin`)) %>% 
  group_by(`Country of Origin`) %>%
  summarize(`Aroma Mean` = mean(Aroma)) #This gives me mean values for each country's aroma reviews

aroma_world_robusta <- merge(countries, aroma_mean_robusta, by.x = "Country of Origin", by.y = "Country of Origin", all.x = TRUE) #This merges the mean values with countries so I can map them
```

```{r robusta mapping}
min(aroma_world_robusta$`Aroma Mean`, na.rm = TRUE)
max(aroma_world_robusta$`Aroma Mean`, na.rm = TRUE)

coffee_palette <- c("#FFEBCD", "#D2B48C", "#8B4513")
aroma_breaks_robusta <- c(6.7, 6.9, 7.1, 7.3, 7.5, 7.8)

aroma_tm_robusta <- tm_shape(aroma_world_robusta) +
  tm_polygons("Aroma Mean", title = "Aroma (Robusta)", palette = coffee_palette, 
              breaks = aroma_breaks_robusta, style = "quantile", id = "Aroma Mean") +
  tm_text("iso_a3", size = "AREA", just = "center") +
  tm_layout() +
  tm_view(text.size.variable = TRUE)


tmap_mode("view")
tmap_leaflet(aroma_tm_robusta)
```

```{r merged tables}
aroma_mean_merged <- aroma_merged %>%
  filter(!is.na(`Country of Origin`)) %>% 
  group_by(`Country of Origin`) %>%
  summarize(`Aroma Mean` = mean(Aroma)) #This gives me mean values for each country's aroma reviews

aroma_world_merged <- merge(countries, aroma_mean_merged, by.x = "Country of Origin", by.y = "Country of Origin", all.x = TRUE) #This merges the mean values with countries so I can map them
```

```{r merged mapping}
min(aroma_world_merged$`Aroma Mean`, na.rm = TRUE)
max(aroma_world_merged$`Aroma Mean`, na.rm = TRUE)

coffee_palette <- c("#FFEBCD", "#D2B48C", "#8B4513")
aroma_breaks_merged <- c(7.1, 7.3, 7.5, 7.8, 8.1, 8.3)

aroma_tm_merged <- tm_shape(aroma_world_merged) +
  tm_polygons("Aroma Mean", title = "Aroma (Merged)", palette = coffee_palette, 
              breaks = aroma_breaks_merged, style = "quantile", id = "Aroma Mean") +
  tm_text("iso_a3", size = "AREA", just = "center") +
  tm_layout() +
  tm_view(text.size.variable = TRUE)


tmap_mode("view")
tmap_leaflet(aroma_tm_merged)
```

