---
title: "Sweetness Mapping"
output: pdf_document
date: "2024-19-04"
---

```{r message = F}
library(tmap)
library(sf)
data("World")
```

```{r arabica tables}
countries <- World %>%
  select(name, iso_a3) %>%
  rename("Country of Origin" = name) #This gives me countries and their locations on the world map

sweetness_mean_arabica <- sweetness_arabica %>%
  filter(!is.na(`Country of Origin`)) %>% #One value didnt have a country paired so I removed it
  group_by(`Country of Origin`) %>%
  summarize(`Sweetness Mean` = mean(Sweetness)) #This gives me mean values for each country's Sweetness reviews

sweetness_world_arabica <- merge(countries, sweetness_mean_arabica, by.x = "Country of Origin", by.y = "Country of Origin", all.x = TRUE) #This merges the mean values with countries so I can map them
```

```{r arabica mapping}
min(sweetness_world_arabica$`Sweetness Mean`, na.rm = TRUE)
max(sweetness_world_arabica$`Sweetness Mean`, na.rm = TRUE)

coffee_palette <- c("#FFEBCD", "#D2B48C", "#8B4513")
sweetness_breaks <- c(6.6, 7.2, 7.8, 8.4, 9.0, 9.6, 10)

sweetness_tm_arabica <- tm_shape(sweetness_world_arabica) +
  tm_polygons("Sweetness Mean", title = "Sweetness (Arabica)", palette = coffee_palette, 
              breaks = sweetness_breaks, style = "quantile", id = "Sweetness Mean") +
  tm_text("iso_a3", size = "AREA", just = "center") +
  tm_layout() +
  tm_view(text.size.variable = TRUE)


tmap_mode("view")
tmap_leaflet(sweetness_tm_arabica)
```

```{r robusta tables}
sweetness_mean_robusta <- sweetness_robusta %>%
  filter(!is.na(`Country of Origin`)) %>% #One value didnt have a country paired so I removed it
  group_by(`Country of Origin`) %>%
  summarize(`Sweetness Mean` = mean(Sweetness)) #This gives me mean values for each country's Sweetness reviews

sweetness_world_robusta <- merge(countries, sweetness_mean_robusta, by.x = "Country of Origin", by.y = "Country of Origin", all.x = TRUE) #This merges the mean values with countries so I can map them
```

```{r robusta mapping}
min(sweetness_world_robusta$`Sweetness Mean`, na.rm = TRUE)
max(sweetness_world_robusta$`Sweetness Mean`, na.rm = TRUE)

coffee_palette <- c("#FFEBCD", "#D2B48C", "#8B4513")
sweetness_breaks_robusta <- c(6.6, 6.9, 7.2, 7.5, 7.8, 8.1)

sweetness_tm_robusta <- tm_shape(sweetness_world_robusta) +
  tm_polygons("Sweetness Mean", title = "Sweetness (Robusta)", palette = coffee_palette, 
              breaks = sweetness_breaks_robusta, style = "quantile", id = "Sweetness Mean") +
  tm_text("iso_a3", size = "AREA", just = "center") +
  tm_layout() +
  tm_view(text.size.variable = TRUE)


tmap_mode("view")
tmap_leaflet(sweetness_tm_robusta)
```


```{r merged tables}
sweetness_mean_merged <- sweetness_merged %>%
  filter(!is.na(`Country of Origin`)) %>% #One value didnt have a country paired so I removed it
  group_by(`Country of Origin`) %>%
  summarize(`Sweetness Mean` = mean(Sweetness)) #This gives me mean values for each country's Sweetness reviews

sweetness_world_merged <- merge(countries, sweetness_mean_merged, by.x = "Country of Origin", by.y = "Country of Origin", all.x = TRUE) #This merges the mean values with countries so I can map them
```

```{r merged mapping}
min(sweetness_world_merged$`Sweetness Mean`, na.rm = TRUE)
max(sweetness_world_merged$`Sweetness Mean`, na.rm = TRUE)

coffee_palette <- c("#FFEBCD", "#D2B48C", "#8B4513")
sweetness_breaks_merged <- c(7.6, 8.0, 8.4, 8.8, 9.2, 9.6, 10)

sweetness_tm_merged <- tm_shape(sweetness_world_merged) +
  tm_polygons("Sweetness Mean", title = "Sweetness (Merged)", palette = coffee_palette, 
              breaks = sweetness_breaks_merged, style = "quantile", id = "Sweetness Mean") +
  tm_text("iso_a3", size = "AREA", just = "center") +
  tm_layout() +
  tm_view(text.size.variable = TRUE)


tmap_mode("view")
tmap_leaflet(sweetness_tm_merged)
```


